### ISSUE TITLE
Compatibility with OJS 3.4

### ISSUE THREAD

**Issue by jonasraoni** [ajnyga/forthcoming#16]
The plugin is missing a release for stable-3_4_0.

PR
- https://github.com/ajnyga/forthcoming/pull/17

**Comment by jonasraoni** [comment]
Hi @ajnyga, could you please review the PR below?

- https://github.com/ajnyga/forthcoming/pull/17

I did some tests here and it seems to be working fine:
- Selected the forthcoming issue, it disappeared from the list of issues
- When attempting to access the issue by ID, I'm redirected to the `/forthcoming` URL
- When viewing an article from the forthcoming issue, I see a `Forthcoming` label on the top

**Comment by ajnyga** [comment]
Thank you for this Jonas.

I have been hopeful that this would be at some point supported in the OJS core (that is publishing without an issue) but in the meanwhile I do think that this hack of using an issue this way is the best approach since it allows us to work with DOIs etc. with little effort.

The downside in my approach is that at some point the forthcoming issue is going to have a lot of articles assigned although the real TOC is never shown for that issue...

**Comment by ajnyga** [comment]
Thanks, merged and released here https://github.com/ajnyga/forthcoming/releases
