### ISSUE TITLE
PDF Plugin

### ISSUE THREAD

**Issue by ohilbig01** [ajnyga/forthcoming#2]
Hi ajnyga,
thank you for this very useful plugin! We would like to use it for one of our journals.
Regarding the the PDF plugin:
The articles are retrieved with the link "forthcoming/article/\d+/\d+", therefore the PdfJsViewer Plugin does nor work.
This is not the case when using "article/view". If the article is included in the statistics count, I think it would be OK.
Do you think using "article/view" implies other side effects?

Best regards

**Comment by ajnyga** [comment]
You are welcome to use the code anyway you want.

I have a feeling the system will complain if there are two identical handlers (article/view) but you can of course try.

In the upcoming OJS versions it will be a lot easier to create a plugin like this. The database design is changing in OJS 3.2 which should be released in the beginning of next year. I will probably do a complete rewrite of this then and hopefully will have support for things like DOIs, statistics, PDF.js and article landing pages as well.

**Comment by ohilbig01** [comment]
OK, thank you, I'll try

**Comment by ajnyga** [comment]
Hi,

Starting to work on this. It would be fairly easy to create a new version that works with 3.2. However, I would like to solve the issue with DOIs and statistics. 

I have a preliminary concept for this:

- I would change the code so that there would be a new selection in Issue settings for setting a particular issue as the "Forthcoming issue". The journal could name this issue as they want. The Forthcoming plugin would remove that issue automatically from the public Issue Archive page and would create a custom Navigation Menu item for a page that would list all articles within that issue
- When publishing a new article in 3.2/3.3 you would first select the Forthcoming issue and publish Version 1 of the article. The DOI of the article would start working and statistics as well, because the official article landing page would be published.
- On the landing page of the article the plugin would add an extra header above the title stating that this is a Ahead of print article to be published later in an issue. 
- When the journal knows the actual issue where the article is going to be published, they can create a new version of the article and choose the correct Future issue and then just Schedule for publication.
- When the actual issue is published, version 2 of the article comes online automatically. The ahead of print version is also still accessible. Most importantly, no statistics lost and DOIs work as expected.

What do you think? This concept would also allow the PDF plugin to work.

**Comment by ohilbig01** [comment]
Hi ajnyga,
this sounds very good. I am not fully familiar with the workflow right now, so I can't really contribute something useful. At the moment we are not using Forthcoming, though we have a customer who would be interested.
Best regards

**Comment by ohilbig01** [comment]
Will the ahead of print version finally be seen on the same article landing page as the official published version? Will it be just another galley (with its own statistics) and will it appear under the label "versions" on article_details?
And what happens after that to the extra menu entry?

**Comment by ajnyga** [comment]
I have added the new version which supports 3.2.1 https://github.com/ajnyga/forthcoming
Note that this is a rewrite of the whole plugin and changes the original concept.

The new version supports DOIs, statistics, pdf.js-plugin etc.
The forthcoming articles are still visible in the same Menu location `/forthcoming/`

I suggest that you test the plugin and see how it works. The README file has a short introduction.
