### ISSUE TITLE
This plugin might not work on OJS 3.2. Is there any solution for this. 

### ISSUE THREAD

**Issue by abargouei** [ajnyga/forthcoming#6]
I recently upgraded to OJS 3.2.0-1. However this interesting plugin does not work. Is there any solution for this? 
Thanks

**Comment by ajnyga** [comment]
Hi,

Starting to work on this. It would be fairly easy to create a new version that works with 3.2. However, I would like to solve the issue with DOIs and statistics.

I have a preliminary concept for this:

I would change the code so that there would be a new selection in Issue settings for setting a particular issue as the "Forthcoming issue". The journal could name this issue as they want. The Forthcoming plugin would remove that issue automatically from the public Issue Archive page and would create a custom Navigation Menu item for a page that would list all articles within that issue
When publishing a new article in 3.2/3.3 you would first select the Forthcoming issue and publish Version 1 of the article. The DOI of the article would start working and statistics as well, because the official article landing page would be published.
On the landing page of the article the plugin would add an extra header above the title stating that this is a Ahead of print article to be published later in an issue.
When the journal knows the actual issue where the article is going to be published, they can create a new version of the article and choose the correct Future issue and then just Schedule for publication.
When the actual issue is published, version 2 of the article comes online automatically. The ahead of print version is also still accessible. Most importantly, no statistics lost and DOIs work as expected.
What do you think?

**Comment by kksabu** [comment]
Highly appreciate development of a new version of the plugin. Kindly consider the following suggestions:

- The suggestion that Ahead of print article to be placed above the title of a forthcoming article is excellent, but it would be inappropriate for an online journal. So another terminology like 'Online first' or any other suitable term may be used in such cases.
- After publishing of the forthcoming articles in an issue, you have mentioned that Ahead of print version will still be accessible. Does it mean that for each article there will be always a version 1 and 2 while we use this plugin? This may be good, but what will happen if there is a change in the article and another version (say version 3) is published?

Thanks again..

**Comment by ajnyga** [comment]
Sorry for the delay, we experienced some problems with our upgrade to 3.2 and have been busy fixing the problems.

I have added the new version which supports 3.2.1 https://github.com/ajnyga/forthcoming
Note that this is a rewrite of the whole plugin and changes the original concept.

**Comment by ajnyga** [comment]
> Highly appreciate development of a new version of the plugin. Kindly consider the following points:
> 
> * The suggestion that Ahead of print article to be placed above the title of a forthcoming article is excellent, but it would be inappropriate for an online journal. So another terminology like 'Online first' or any other suitable term may be used in such cases.
> * After publishing of the forthcoming articles in an issue, you have mentioned that Ahead of print version will still be accessible. Does it mean that for each article there will be always a version 1 and 2 while we use this plugin? This may be good, but what will happen if there is a change in the article and another version (say version 3) is published?
> 
> Thanks again..

The language is quite easy to edit in the locale files if you prefer some other use of words. 

The plugin uses the versioning feature in OJS. Version 1 is the Forthcoming version and version 2 is the final published one. But technically you can have any amount of versions after version 2 (although in general I would not take adding new article versions too lightly).

You can also unpublish version 1 (Forthcoming version) after version 2 is published if you want.

**Comment by kksabu** [comment]
That's really good news. Have you or anyone tested with OJS 3.3.0-6 ?

**Comment by ajnyga** [comment]
Not yet, but planning to do that in June. I think there is a good chance it will work.

**Comment by ajnyga** [comment]
The new concept has it's downsides, but I am hoping that we will see better support for such a feature in the OJS core and I think the way the plugin works now would be fairly close to the solution we would have in the core (I mean the use of versions).
