### ISSUE TITLE
I have facing issue on OJS 3.2 version. It is not working forthcoming plugin 

### ISSUE THREAD

**Issue by shahidasghar90** [ajnyga/forthcoming#7]
Hi, @ajnyga 
I am using OJS 3.2. I have installed Forthcoming article but that is working on this version. Could you please resolve this issue. Your plugin is very interesting and helpful for the journal.
Thanks in advance

Best Regards,
Shahid Asghar

**Comment by marcellamonreale** [comment]
Hi, I have the same problem. With version OJS 3.2.0.2 when I add the link to view the forthcoming article I see the error:

Unrecognized DAO PublishedArticleDAO!

Do you have any update?

Thanks,
Marcella

**Comment by ajnyga** [comment]
Hi,

Starting to work on this. It would be fairly easy to create a new version that works with 3.2. However, I would like to solve the issue with DOIs and statistics. 

I have a preliminary concept for this:

- I would change the code so that there would be a new selection in Issue settings for setting a particular issue as the "Forthcoming issue". The journal could name this issue as they want. The Forthcoming plugin would remove that issue automatically from the public Issue Archive page and would create a custom Navigation Menu item for a page that would list all articles within that issue
- When publishing a new article in 3.2/3.3 you would first select the Forthcoming issue and publish Version 1 of the article. The DOI of the article would start working and statistics as well, because the official article landing page would be published.
- On the landing page of the article the plugin would add an extra header above the title stating that this is a Ahead of print article to be published later in an issue. 
- When the journal knows the actual issue where the article is going to be published, they can create a new version of the article and choose the correct Future issue and then just Schedule for publication.
- When the actual issue is published, version 2 of the article comes online automatically. The ahead of print version is also still accessible. Most importantly, no statistics lost and DOIs work as expected.

What do you think?

**Comment by agm-ls** [comment]
It sounds great. I´ll be waiting this update (maybe even for 3.3 release).
I hope you find time to have it soon as its exactly what we need.
Thank you very much for this amazing plugin

**Comment by ShubashBiswas** [comment]
Hello, 

Hope you very well. We used the plugin but after upgrading to 3.2 and 3.3. Not able to use your plugin. Few authors still asking about this feature now. I can understand the future planning of this plugin. It's a request to you that please make this plugin compatible with OJS 3.3 or later version. You can update the plugin after that work on the feature. That will remove the complexity. We hope you will find the solution. 

Wish you a Good life

**Comment by ajnyga** [comment]
I am just working on this. The plugin will work as described above. Should be ready by tomorrow.

**Comment by ShubashBiswas** [comment]
Hi, 

I hope you starting to work on this. I come with an optional feature. If it is possible to implement please try to show 2-3 upcoming article at journal home page before the current issue section. 

![image](https://user-images.githubusercontent.com/79921627/118385311-ac938800-b62f-11eb-8d6f-09b1f5b6baee.png)

**Comment by waqas1223** [comment]
> I am just working on this. The plugin will work as described above. Should be ready by tomorrow.

sir we are waited for it.

**Comment by twaseem-art** [comment]
> I am just working on this. The plugin will work as described above. Should be ready by tomorrow.

Dear ajnyga, deperately waiting for the plugin for PJS 3.2. 

Regards

**Comment by twaseem-art** [comment]
@ajnyga Dear ajnyga, desperately waiting for the plugin for PJS 3.2.

Regards

**Comment by ajnyga** [comment]
Sorry for the delay, we experienced some problems with our upgrade to 3.2 and have been busy fixing the problems.

I have added the new version which supports 3.2.1 https://github.com/ajnyga/forthcoming
Note that this is a rewrite of the whole plugin and changes the original concept.

**Comment by twaseem-art** [comment]
> Sorry for the delay, we experienced some problems with our upgrade to 3.2 and have been busy fixing the problems.
> 
> I have added the new version which supports 3.2.1 https://github.com/ajnyga/forthcoming
> Note that this is a rewrite of the whole plugin and changes the original concept.

Dear Antti-Jussi Nygard: 

Wonderful and thanks very much for the plugin, which works ok, however the Forthcoming (Article in Press) does not show any content. Would you like to advise on it? Regards

Dr Talat Waseem FRCS Eng, FACS, DM Harvard, MME.
![image](https://user-images.githubusercontent.com/84850230/119831608-e2314e80-bf16-11eb-9922-55a98ef3b1b6.png)
![image](https://user-images.githubusercontent.com/84850230/119831673-f1180100-bf16-11eb-9a1d-70351662f515.png)
![image](https://user-images.githubusercontent.com/84850230/119831728-fd9c5980-bf16-11eb-8905-f0d1c1b21377.png)

**Comment by twaseem-art** [comment]
Thank you all... with selection of remote URL in navigation menu, the Plugin works perfectly. @ajnyga @ShubashBiswas 
Bravo.... Special thanks to @ajnyga
